#ifndef _LIGHTRAY_PREPROCESSOR_COMMON_CONCAT_HPP_
#define _LIGHTRAY_PREPROCESSOR_COMMON_CONCAT_HPP_

#define LIGHTRAY_PP_CONCAT(a, b) _LIGHTRAY_PP_CONCAT(a, b)
#define _LIGHTRAY_PP_CONCAT(a, b) a##b

#endif
