#ifndef _LIGHTRAY_PREPROCESSOR_COMMON_STRINGIZE_HPP_
#define _LIGHTRAY_PREPROCESSOR_COMMON_STRINGIZE_HPP_

#define LIGHTRAY_PP_STRINGIZE(...) _LIGHTRAY_PP_STRINGIZE(__VA_ARGS__)
#define _LIGHTRAY_PP_STRINGIZE(...) #__VA_ARGS__

#endif
