#ifndef _LIGHTRAY_PREPROCESSOR_COMMON_SYMBOLS_HPP_
#define _LIGHTRAY_PREPROCESSOR_COMMON_SYMBOLS_HPP_

#define LIGHTRAY_PP_COMMA() ,
#define LIGHTRAY_PP_LEFT_PAREN() (
#define LIGHTRAY_PP_RIGHT_PARENT() )

#endif
