#ifndef _LIGHTRAY_PREPROCESSOR_SEQ_FIRST_HPP_
#define _LIGHTRAY_PREPROCESSOR_SEQ_FIRST_HPP_


#include <lightray/preprocessor/common/defer.hpp>


#define LIGHTRAY_PP_SEQ_FIRST(seq) _LIGHTRAY_PP_SEQ_FIRST_EXPAND( \
        LIGHTRAY_PP_DEFER(_LIGHTRAY_PP_SEQ_FIRST_HELPER_0)( \
            _LIGHTRAY_PP_SEQ_FIRST_HELPER_1 seq \
        ) \
    ) 

#define _LIGHTRAY_PP_D_SEQ_FIRST(seq) LIGHTRAY_PP_DEFER(LIGHTRAY_PP_SEQ_FIRST)(seq)


#define _LIGHTRAY_PP_SEQ_FIRST_EXPAND(...) __VA_ARGS__
#define _LIGHTRAY_PP_SEQ_FIRST_HELPER_0(head, ...) head
#define _LIGHTRAY_PP_SEQ_FIRST_HELPER_1(...) (__VA_ARGS__),


#endif
