#ifndef _LIGHTRAY_PREPROCESSOR_VAR_ELEM_HPP_
#define _LIGHTRAY_PREPROCESSOR_VAR_ELEM_HPP_

#include <lightray/preprocessor/common.hpp>

/*
 * Expands to the n-th element of the variadic arguments.
 * If n is more than or equal to the number of variadic arguments,
 * then this macro expands to nothing.
 *
 * Author: P. Lutchanont
 */
#define LIGHTRAY_PP_VAR_ELEM(n, ...) LIGHTRAY_PP_CAT(LIGHTRAY_PP_VAR_ELEM_, n)(__VA_ARGS__)

#define LIGHTRAY_PP_VAR_ELEM_0(e, ...) e
#define LIGHTRAY_PP_VAR_ELEM_1(e, ...) LIGHTRAY_PP_VAR_ELEM_0(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_2(e, ...) LIGHTRAY_PP_VAR_ELEM_1(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_3(e, ...) LIGHTRAY_PP_VAR_ELEM_2(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_4(e, ...) LIGHTRAY_PP_VAR_ELEM_3(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_5(e, ...) LIGHTRAY_PP_VAR_ELEM_4(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_6(e, ...) LIGHTRAY_PP_VAR_ELEM_5(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_7(e, ...) LIGHTRAY_PP_VAR_ELEM_6(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_8(e, ...) LIGHTRAY_PP_VAR_ELEM_7(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_9(e, ...) LIGHTRAY_PP_VAR_ELEM_8(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_10(e, ...) LIGHTRAY_PP_VAR_ELEM_9(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_11(e, ...) LIGHTRAY_PP_VAR_ELEM_10(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_12(e, ...) LIGHTRAY_PP_VAR_ELEM_11(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_13(e, ...) LIGHTRAY_PP_VAR_ELEM_12(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_14(e, ...) LIGHTRAY_PP_VAR_ELEM_13(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_15(e, ...) LIGHTRAY_PP_VAR_ELEM_14(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_16(e, ...) LIGHTRAY_PP_VAR_ELEM_15(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_17(e, ...) LIGHTRAY_PP_VAR_ELEM_16(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_18(e, ...) LIGHTRAY_PP_VAR_ELEM_17(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_19(e, ...) LIGHTRAY_PP_VAR_ELEM_18(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_20(e, ...) LIGHTRAY_PP_VAR_ELEM_19(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_21(e, ...) LIGHTRAY_PP_VAR_ELEM_20(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_22(e, ...) LIGHTRAY_PP_VAR_ELEM_21(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_23(e, ...) LIGHTRAY_PP_VAR_ELEM_22(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_24(e, ...) LIGHTRAY_PP_VAR_ELEM_23(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_25(e, ...) LIGHTRAY_PP_VAR_ELEM_24(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_26(e, ...) LIGHTRAY_PP_VAR_ELEM_25(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_27(e, ...) LIGHTRAY_PP_VAR_ELEM_26(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_28(e, ...) LIGHTRAY_PP_VAR_ELEM_27(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_29(e, ...) LIGHTRAY_PP_VAR_ELEM_28(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_30(e, ...) LIGHTRAY_PP_VAR_ELEM_29(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_31(e, ...) LIGHTRAY_PP_VAR_ELEM_30(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_32(e, ...) LIGHTRAY_PP_VAR_ELEM_31(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_33(e, ...) LIGHTRAY_PP_VAR_ELEM_32(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_34(e, ...) LIGHTRAY_PP_VAR_ELEM_33(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_35(e, ...) LIGHTRAY_PP_VAR_ELEM_34(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_36(e, ...) LIGHTRAY_PP_VAR_ELEM_35(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_37(e, ...) LIGHTRAY_PP_VAR_ELEM_36(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_38(e, ...) LIGHTRAY_PP_VAR_ELEM_37(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_39(e, ...) LIGHTRAY_PP_VAR_ELEM_38(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_40(e, ...) LIGHTRAY_PP_VAR_ELEM_39(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_41(e, ...) LIGHTRAY_PP_VAR_ELEM_40(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_42(e, ...) LIGHTRAY_PP_VAR_ELEM_41(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_43(e, ...) LIGHTRAY_PP_VAR_ELEM_42(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_44(e, ...) LIGHTRAY_PP_VAR_ELEM_43(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_45(e, ...) LIGHTRAY_PP_VAR_ELEM_44(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_46(e, ...) LIGHTRAY_PP_VAR_ELEM_45(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_47(e, ...) LIGHTRAY_PP_VAR_ELEM_46(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_48(e, ...) LIGHTRAY_PP_VAR_ELEM_47(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_49(e, ...) LIGHTRAY_PP_VAR_ELEM_48(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_50(e, ...) LIGHTRAY_PP_VAR_ELEM_49(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_51(e, ...) LIGHTRAY_PP_VAR_ELEM_50(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_52(e, ...) LIGHTRAY_PP_VAR_ELEM_51(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_53(e, ...) LIGHTRAY_PP_VAR_ELEM_52(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_54(e, ...) LIGHTRAY_PP_VAR_ELEM_53(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_55(e, ...) LIGHTRAY_PP_VAR_ELEM_54(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_56(e, ...) LIGHTRAY_PP_VAR_ELEM_55(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_57(e, ...) LIGHTRAY_PP_VAR_ELEM_56(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_58(e, ...) LIGHTRAY_PP_VAR_ELEM_57(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_59(e, ...) LIGHTRAY_PP_VAR_ELEM_58(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_60(e, ...) LIGHTRAY_PP_VAR_ELEM_59(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_61(e, ...) LIGHTRAY_PP_VAR_ELEM_60(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_62(e, ...) LIGHTRAY_PP_VAR_ELEM_61(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_63(e, ...) LIGHTRAY_PP_VAR_ELEM_62(__VA_ARGS__)
#define LIGHTRAY_PP_VAR_ELEM_64(e, ...) LIGHTRAY_PP_VAR_ELEM_63(__VA_ARGS__)

#endif
