#ifndef _LIGHTRAY_PREPROCESSOR_VAR_FOR_EACH_HPP_
#define _LIGHTRAY_PREPROCESSOR_VAR_FOR_EACH_HPP_

#include <lightray/preprocessor/common.hpp>
#include <lightray/preprocessor/arithmetic/inc.hpp>

#include "elem.hpp"
#include "rest_n.hpp"
#include "size.hpp"

#define LIGHTRAY_PP_VAR_FOR_EACH(macro, data, ...) \
  LIGHTRAY_PP_VAR_FOR_EACH_EXPAND( \
    LIGHTRAY_PP_CAT(LIGHTRAY_PP_VAR_FOR_EACH_, LIGHTRAY_PP_VAR_SIZE(__VA_ARGS__))(macro, data, 0, __VA_ARGS__) \
  )

#define LIGHTRAY_PP_VAR_FOR_EACH_EXPAND(...) __VA_ARGS__

#define LIGHTRAY_PP_VAR_FOR_EACH_0(macro, data, i, ...)
#define LIGHTRAY_PP_VAR_FOR_EACH_1(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_0(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_2(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_1(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_3(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_2(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_4(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_3(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_5(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_4(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_6(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_5(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_7(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_6(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_8(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_7(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_9(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_8(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_10(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_9(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_11(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_10(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_12(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_11(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_13(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_12(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_14(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_13(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_15(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_14(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_16(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_15(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_17(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_16(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_18(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_17(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_19(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_18(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_20(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_19(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_21(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_20(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_22(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_21(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_23(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_22(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_24(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_23(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_25(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_24(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_26(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_25(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_27(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_26(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_28(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_27(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_29(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_28(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_30(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_29(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_31(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_30(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_32(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_31(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_33(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_32(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_34(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_33(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_35(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_34(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_36(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_35(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_37(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_36(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_38(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_37(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_39(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_38(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_40(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_39(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_41(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_40(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_42(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_41(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_43(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_42(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_44(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_43(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_45(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_44(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_46(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_45(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_47(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_46(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_48(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_47(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_49(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_48(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_50(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_49(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_51(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_50(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_52(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_51(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_53(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_52(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_54(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_53(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_55(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_54(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_56(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_55(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_57(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_56(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_58(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_57(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_59(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_58(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_60(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_59(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_61(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_60(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_62(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_61(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_63(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_62(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))
#define LIGHTRAY_PP_VAR_FOR_EACH_64(macro, data, i, ...) LIGHTRAY_PP_DEFER(macro)(data, i, LIGHTRAY_PP_VAR_ELEM(0, __VA_ARGS__)) LIGHTRAY_PP_VAR_FOR_EACH_63(macro, data, LIGHTRAY_PP_INC(i), LIGHTRAY_PP_VAR_REST_N(1, __VA_ARGS__))


#endif
