#ifndef _LIGHTRAY_PREPROCESSOR_COMMON_HPP_
#define _LIGHTRAY_PREPROCESSOR_COMMON_HPP_

#define LIGHTRAY_PP_CAT(a, b) LIGHTRAY_PP_CAT_(a, b)
#define LIGHTRAY_PP_CAT_(a, b) a##b

#define LIGHTRAY_PP_STRINGIZE(...) LIGHTRAY_PP_STRINGIZE_(__VA_ARGS__)
#define LIGHTRAY_PP_STRINGIZE_(...) #__VA_ARGS__

#define LIGHTRAY_PP_EMPTY(...)
#define LIGHTRAY_PP_DEFER(...) __VA_ARGS__ LIGHTRAY_PP_EMPTY()
#define LIGHTRAY_PP_EXPAND(...) __VA_ARGS__

#define LIGHTRAY_PP_COMMA() ,

#endif
